# Generated by Django 3.2.5 on 2021-07-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Address', models.TextField()),
                ('Appointment_date', models.DateField()),
                ('Appointment_time', models.TimeField()),
                ('Disease', models.CharField(max_length=50)),
                ('Vaccinated', models.BooleanField()),
            ],
        ),
    ]
