# Generated by Django 3.2.5 on 2021-07-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_time',
            field=models.CharField(max_length=56),
        ),
    ]
