# Generated by Django 3.2.5 on 2021-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20210716_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Address',
            field=models.CharField(max_length=200),
        ),
    ]
