# Generated by Django 3.2.5 on 2021-07-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='Register',
            new_name='Select_Your_UserId',
        ),
    ]
