# Generated by Django 3.2.5 on 2021-07-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_register_personalinfo_select_your_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='Select_Your_UserId',
            new_name='Select_Your_User_Id',
        ),
    ]
