# Generated by Django 3.2.5 on 2021-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_select_your_userid_personalinfo_select_your_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Gender',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
