# Generated by Django 3.2.5 on 2021-07-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210717_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Full_Name',
        ),
    ]
