# Generated by Django 3.2.5 on 2021-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_personalinfo_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('vaccine', models.CharField(max_length=10)),
            ],
        ),
    ]
