# Generated by Django 3.2.5 on 2021-07-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_appointment_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Disease',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
