# Generated by Django 3.2.5 on 2021-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='Other',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
