# Generated by Django 3.2.5 on 2021-07-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
