# Generated by Django 3.2.5 on 2021-07-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210722_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
