# Generated by Django 3.2.5 on 2021-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
