# Generated by Django 3.2.5 on 2021-07-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
    ]
