# Generated by Django 3.2.5 on 2021-07-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payments',
        ),
    ]
