# Generated by Django 3.2.5 on 2021-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_payment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_token',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
